services:
    app:
        build:
            context: docker
            dockerfile: Dockerfile
        container_name: dinner-bot-app
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - dinner-bot

    db:
        image: postgres:15
        container_name: dinner-bot-db
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5436:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - dinner-bot

    nginx:
        image: nginx:alpine
        container_name: dinner-bot-nginx
        ports:
            - "88:80"
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:  # Added missing network
            - dinner-bot

# Removed ngrok service - will run locally instead

volumes:
    pgdata:

networks:
    dinner-bot:
