services:
    app:
        build:
            context: docker
            dockerfile: Dockerfile
        container_name: dinner-bot-app
        volumes:
            - .:/var/www
        depends_on:
            - db
            - redis
        networks:
            - dinner-bot

    db:
        image: postgres:15
        container_name: dinner-bot-db
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5436:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - dinner-bot

    redis:
        image: redis:alpine
        container_name: dinner-bot-redis
        ports:
            -   "6379:6379"
        volumes:
            -   redisdata:/data
        restart: unless-stopped
        networks:
            - dinner-bot

    nginx:
        image: nginx:alpine
        container_name: dinner-bot-nginx
        ports:
            - "88:80"
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - dinner-bot

volumes:
    pgdata:
    redisdata:

networks:
    dinner-bot:
